branch-defaults:
  default:
    environment: genas-env
    group_suffix: null
  main:
    environment: genas-env
    group_suffix: null
  master:
    environment: genas-241101a
environment-defaults:
  genas-env:
    branch: null
    repository: null
  genas-prod:
    branch: null
    repository: null
global:
  application_name: genas
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
